//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/05_Script/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""L_Boy"",
            ""id"": ""08817020-b375-4f06-a318-23e05cc6bbca"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""a63b1707-5e5e-459b-8c63-631f8078dca5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""67d24400-7f2b-4a8a-8c76-2dcbec4819b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""f9def735-e881-4ba8-814c-fac77db370e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""d4911278-0033-4c4c-9a2c-065e057a0530"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""0883255b-3fff-44bf-8f07-e104744d761a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Luminosity"",
                    ""type"": ""Button"",
                    ""id"": ""1d1477af-16a3-48bd-b39f-91ea7827ab0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Resume"",
                    ""type"": ""Button"",
                    ""id"": ""62ee43d6-bb63-49e4-bc2e-918a34bfc852"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""37198eb6-3165-4ce3-9a46-3cb8993bbc62"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""429847f6-9bf9-4c44-9c9b-0f3ced10bbbd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""73f96191-7e7d-4d4e-b6b9-cb7cc7373d21"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8a414feb-9f7c-42fd-8dbb-36c09a38d2a9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6d8752f8-3f2e-4b2c-8a15-ccac3fd3896c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2d50a1e7-1a2b-45b8-bdd9-fb5d50df62a7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c5c9fe6d-0383-4468-9281-76aae41c9697"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f51c7c80-9369-4e8e-b6ed-2c56c8a49425"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68b85c61-fcc1-47f0-aaac-3491454dafac"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4bf68de-9e15-4c91-871e-9f1bbefde9e7"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26018bbd-93ff-40c8-8cb6-154c76b752bc"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6798f1e-3c5b-43f8-b496-69da407bca12"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab30488e-da1c-470e-b647-294a0a623a1d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff931700-3800-4263-aae8-c73611bcbaf1"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7cb82e2-0aa9-4c93-8065-2feeda032064"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Luminosity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43efb9b7-0390-449e-a36b-520fd8980b9f"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Luminosity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20288e50-b684-483c-bd1e-b53020d0a2ef"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Resume"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""132fbe95-fa46-4c96-a23d-a02458303a78"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Resume"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // L_Boy
        m_L_Boy = asset.FindActionMap("L_Boy", throwIfNotFound: true);
        m_L_Boy_Move = m_L_Boy.FindAction("Move", throwIfNotFound: true);
        m_L_Boy_Run = m_L_Boy.FindAction("Run", throwIfNotFound: true);
        m_L_Boy_Jump = m_L_Boy.FindAction("Jump", throwIfNotFound: true);
        m_L_Boy_Interact = m_L_Boy.FindAction("Interact", throwIfNotFound: true);
        m_L_Boy_Attack = m_L_Boy.FindAction("Attack", throwIfNotFound: true);
        m_L_Boy_Luminosity = m_L_Boy.FindAction("Luminosity", throwIfNotFound: true);
        m_L_Boy_Resume = m_L_Boy.FindAction("Resume", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // L_Boy
    private readonly InputActionMap m_L_Boy;
    private IL_BoyActions m_L_BoyActionsCallbackInterface;
    private readonly InputAction m_L_Boy_Move;
    private readonly InputAction m_L_Boy_Run;
    private readonly InputAction m_L_Boy_Jump;
    private readonly InputAction m_L_Boy_Interact;
    private readonly InputAction m_L_Boy_Attack;
    private readonly InputAction m_L_Boy_Luminosity;
    private readonly InputAction m_L_Boy_Resume;
    public struct L_BoyActions
    {
        private @PlayerInput m_Wrapper;
        public L_BoyActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_L_Boy_Move;
        public InputAction @Run => m_Wrapper.m_L_Boy_Run;
        public InputAction @Jump => m_Wrapper.m_L_Boy_Jump;
        public InputAction @Interact => m_Wrapper.m_L_Boy_Interact;
        public InputAction @Attack => m_Wrapper.m_L_Boy_Attack;
        public InputAction @Luminosity => m_Wrapper.m_L_Boy_Luminosity;
        public InputAction @Resume => m_Wrapper.m_L_Boy_Resume;
        public InputActionMap Get() { return m_Wrapper.m_L_Boy; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(L_BoyActions set) { return set.Get(); }
        public void SetCallbacks(IL_BoyActions instance)
        {
            if (m_Wrapper.m_L_BoyActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnMove;
                @Run.started -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnRun;
                @Jump.started -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnJump;
                @Interact.started -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnInteract;
                @Attack.started -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnAttack;
                @Luminosity.started -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnLuminosity;
                @Luminosity.performed -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnLuminosity;
                @Luminosity.canceled -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnLuminosity;
                @Resume.started -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnResume;
                @Resume.performed -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnResume;
                @Resume.canceled -= m_Wrapper.m_L_BoyActionsCallbackInterface.OnResume;
            }
            m_Wrapper.m_L_BoyActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Luminosity.started += instance.OnLuminosity;
                @Luminosity.performed += instance.OnLuminosity;
                @Luminosity.canceled += instance.OnLuminosity;
                @Resume.started += instance.OnResume;
                @Resume.performed += instance.OnResume;
                @Resume.canceled += instance.OnResume;
            }
        }
    }
    public L_BoyActions @L_Boy => new L_BoyActions(this);
    public interface IL_BoyActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnLuminosity(InputAction.CallbackContext context);
        void OnResume(InputAction.CallbackContext context);
    }
}
